### ISSUE TITLE
Option to reduce quality/size of screen shots?

### ISSUE THREAD

**Issue by aarondunn** [aarondunn/simpleshare#67]
I was thinking, maybe we should add an option (on by default) to reduce the size of images so they upload much faster?

When i take a screenshot of my desktop, its quite big being a png, like several mb. What do you think if we try default like 80% jpeg?

Examples
![jpeg](https://cloud.githubusercontent.com/assets/3102237/5289475/fb12cc9a-7af2-11e4-8d9e-8416f3faf8d4.jpg)
![original](https://cloud.githubusercontent.com/assets/3102237/5289474/fb104d8a-7af2-11e4-8acd-e68568035a68.png)

**Comment by aarondunn** [comment]
@Rognarroc thoughts on this for the next release?

**Comment by Rognarroc** [comment]
There is not a problem to save image as jpeg from app. The problem is: the only option to take fullscreen in current version of app: use cmd+shift+3 hotkey. Actually, this is a default system screenshot hotkey, so fullscreen screenshot is made by system, not by our app,  and placed to desktop. Out app polls desktop for new files and uploads screenshot made by system. As a result, we cannot change format of fullscreen screenshot from within our app.

**Comment by aarondunn** [comment]
but we can take png, compress, and upload right?

**Comment by Rognarroc** [comment]
Sure, i sent you a sample build.

**Comment by aarondunn** [comment]
where did we end up with this? is it live?

**Comment by aarondunn** [comment]
@Rognarroc FYI this  was the original task for this "compress images" option.
